name: model3d
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_cube: ^0.1.1
  animated_card: ^2.0.0
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jet/robo/
    - assets/jet/Zebra/
    - assets/jet/house/
    - assets/jet/Cow/
    - assets/jet/littleFish/
    - assets/jet/littleMan/
    - assets/jet/car/
    - assets/jet/policeCar/
    - assets/jet/ballPark/
    - assets/jet/spermWhale/
    - assets/jet/finback/
    - assets/jet/elephant/
    - assets/jet/penguin/
    - assets/jet/penguins/
    - assets/jet/pepermint/
    - assets/jet/viking/
    - assets/jet/wasp/
    - assets/jet/butterfly/
    - assets/jet/monkey/
    - assets/jet/velociRobot/
    - assets/jet/turtle/
    - assets/jet/robotAndSnail/
    - assets/jet/toyRobot/
    - assets/jet/skunk/
    - assets/jet/deer/

  